version: "3.1"

services:
  home:
    container_name: home
    build: ./home
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true

  users:
    container_name: users
    build: ./users
    ports:
      - "3002:3002"
    environment:
      - CHOKIDAR_USEPOLLING=true
